// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"OutTiktok/apps/user/internal/logic"
	"OutTiktok/apps/user/internal/svc"
	"OutTiktok/apps/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginRes, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) User(ctx context.Context, in *user.UserReq) (*user.UserRes, error) {
	l := logic.NewUserLogic(ctx, s.svcCtx)
	return l.User(in)
}

func (s *UserServer) GetUsers(ctx context.Context, in *user.GetUsersReq) (*user.GetUsersRes, error) {
	l := logic.NewGetUsersLogic(ctx, s.svcCtx)
	return l.GetUsers(in)
}
