// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"OutTiktok/apps/relation/internal/logic"
	"OutTiktok/apps/relation/internal/svc"
	"OutTiktok/apps/relation/relation"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServer) Action(ctx context.Context, in *relation.ActionReq) (*relation.ActionRes, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *RelationServer) FollowList(ctx context.Context, in *relation.FollowListReq) (*relation.FollowListRes, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *RelationServer) FollowerList(ctx context.Context, in *relation.FollowerListReq) (*relation.FollowerListRes, error) {
	l := logic.NewFollowerListLogic(ctx, s.svcCtx)
	return l.FollowerList(in)
}

func (s *RelationServer) FriendList(ctx context.Context, in *relation.FriendListReq) (*relation.FriendListRes, error) {
	l := logic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}

func (s *RelationServer) GetRelations(ctx context.Context, in *relation.GetRelationsReq) (*relation.GetRelationsRes, error) {
	l := logic.NewGetRelationsLogic(ctx, s.svcCtx)
	return l.GetRelations(in)
}
