// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"OutTiktok/apps/message/internal/logic"
	"OutTiktok/apps/message/internal/svc"
	"OutTiktok/apps/message/message"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Action(ctx context.Context, in *message.MessageActionReq) (*message.MessageActionRes, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *MessageServer) Chat(ctx context.Context, in *message.MessageChatReq) (*message.MessageChatRes, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

func (s *MessageServer) GetLastMsg(ctx context.Context, in *message.GetLastMsgReq) (*message.GetLastMsgRes, error) {
	l := logic.NewGetLastMsgLogic(ctx, s.svcCtx)
	return l.GetLastMsg(in)
}
