// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package favoriteclient

import (
	"context"

	"OutTiktok/apps/favorite/favorite"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionReq           = favorite.ActionReq
	ActionRes           = favorite.ActionRes
	GetUserFavoriteReq  = favorite.GetUserFavoriteReq
	GetUserFavoriteRes  = favorite.GetUserFavoriteRes
	GetVideoFavoriteReq = favorite.GetVideoFavoriteReq
	GetVideoFavoriteRes = favorite.GetVideoFavoriteRes
	ListReq             = favorite.ListReq
	ListRes             = favorite.ListRes
	UserFavorite        = favorite.UserFavorite
	UserInfo            = favorite.UserInfo
	Video               = favorite.Video
	VideoFavorite       = favorite.VideoFavorite

	Favorite interface {
		Action(ctx context.Context, in *ActionReq, opts ...grpc.CallOption) (*ActionRes, error)
		List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListRes, error)
		GetVideoFavorite(ctx context.Context, in *GetVideoFavoriteReq, opts ...grpc.CallOption) (*GetVideoFavoriteRes, error)
		GetUserFavorite(ctx context.Context, in *GetUserFavoriteReq, opts ...grpc.CallOption) (*GetUserFavoriteRes, error)
	}

	defaultFavorite struct {
		cli zrpc.Client
	}
)

func NewFavorite(cli zrpc.Client) Favorite {
	return &defaultFavorite{
		cli: cli,
	}
}

func (m *defaultFavorite) Action(ctx context.Context, in *ActionReq, opts ...grpc.CallOption) (*ActionRes, error) {
	client := favorite.NewFavoriteClient(m.cli.Conn())
	return client.Action(ctx, in, opts...)
}

func (m *defaultFavorite) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListRes, error) {
	client := favorite.NewFavoriteClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

func (m *defaultFavorite) GetVideoFavorite(ctx context.Context, in *GetVideoFavoriteReq, opts ...grpc.CallOption) (*GetVideoFavoriteRes, error) {
	client := favorite.NewFavoriteClient(m.cli.Conn())
	return client.GetVideoFavorite(ctx, in, opts...)
}

func (m *defaultFavorite) GetUserFavorite(ctx context.Context, in *GetUserFavoriteReq, opts ...grpc.CallOption) (*GetUserFavoriteRes, error) {
	client := favorite.NewFavoriteClient(m.cli.Conn())
	return client.GetUserFavorite(ctx, in, opts...)
}
