// Code generated by goctl. DO NOT EDIT.
// Source: publish.proto

package server

import (
	"context"

	"OutTiktok/apps/publish/internal/logic"
	"OutTiktok/apps/publish/internal/svc"
	"OutTiktok/apps/publish/publish"
)

type PublishServer struct {
	svcCtx *svc.ServiceContext
	publish.UnimplementedPublishServer
}

func NewPublishServer(svcCtx *svc.ServiceContext) *PublishServer {
	return &PublishServer{
		svcCtx: svcCtx,
	}
}

func (s *PublishServer) Action(ctx context.Context, in *publish.ActionReq) (*publish.ActionRes, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *PublishServer) List(ctx context.Context, in *publish.ListReq) (*publish.ListRes, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *PublishServer) GetVideos(ctx context.Context, in *publish.GetVideosReq) (*publish.GetVideosRes, error) {
	l := logic.NewGetVideosLogic(ctx, s.svcCtx)
	return l.GetVideos(in)
}
